keyboarddatabase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name = 'home'),
path('about/', views.about, name = 'about'),
path('keyboards/', views.keyboards_index, name = 'keyboards_index'),
path('keyboards/create/', views.KeyboardCreate.as_view(), name = 'keyboards_create'),
path('keyboard/<int:keyboard_id>/', views.keyboards_detail, name='detail'),
path('keyboard/<int:pk>/delete/', views.KeyboardDelete.as_view(), name='keyboards_delete'),
path('keyboards/<int:pk>/update/', views.KeyboardUpdate.as_view(), name = 'keyboards_update'),
path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# from django.config import settings

# Create your models here.
COLORS = (
    ('BLA','Black'),
    ('RED', "Red"),
    ('WHI', 'White'),
    ('BLU','Blue'),
    ('GRN', 'Green'),
    ('YLW','Yellow'),
    ('PRP', 'Purple'),
    ('ORG','Orange')
)

CASE_MATERIALS = (
    ('PLA','Plastic'),
    ('POLY', "Polycarbonate"),
    ('ALU', 'Aluminum'),
    ('ACR', 'Acrylic'),
    ('WOOD','Wood')
)

CASE_SIZE = (
    ('100','Full Size'),
    ('80', "TKL"),
    ('75', '75%'),
    ('65','65%'),
    ('60', "60%"),
    ('40', '40%'),
)

CASE_LAYOUT = (
    ('ANSI','ANSI'),
    ('ISO', "Isometric"),
    ('ORTHO', 'Ortholinear'),
)

PLATE_MATERIAL = (
    ('ALU','Aluminum'),
    ('BRS', "Brass"),
    ('STL', 'Steel'),
    ('CBF','Carbon Fiber')
)

SWITCH_STYLE = (
    ('CLI','Clicky'),
    ('SIL', "Silent"),
    ('LIN', 'Linear'),
    ('TAC', 'Tactile'),
    ('OPT', 'Optical'),
)

TRUE_FALSE = (
    ('TRUE','Yes'),
    ('FALSE', "No"),
)


class Keyboard(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

    Case_Color = models.CharField(
        max_length=20,
        choices = COLORS,
        default= 'BLA'
        )
    Case_Material = models.CharField(
        max_length = 20,
        choices = CASE_MATERIALS,
        default='ALU'
        )
    Case_Size = models.CharField(
        max_length=20,
        choices = CASE_SIZE,
        default='100'
        )
    
    Case_Layout = models.CharField(
        max_length= 20,
        choices = CASE_LAYOUT,
        default='ANSI'
        )
    Plate_Name = models.CharField(
        max_length= 20,
        default = 'Glorious'
        )
    Plate_Color = models.CharField(
        max_length= 20,
        choices = COLORS,
        default='BLA'
        )
    Plate_Material = models.CharField(
        max_length= 20,
        choices = PLATE_MATERIAL,
        default='ALU'
        )
    Switch_Name = models.CharField(
        max_length= 20,
        default = 'Cherry MX'
        )
    Switch_Color = models.CharField(
        max_length= 20,
        choices = COLORS,
        default='BLA'
        )
    Switch_Style = models.CharField(
        max_length= 20,
        choices = SWITCH_STYLE,
        default='LIN'
        )
    Switch_RGB = models.CharField(
        max_length= 20,
        choices = TRUE_FALSE,
        default='TRUE'
        )
    Keycap_Name = models.CharField(
        max_length= 20,
        default = 'GMK'
        )
    Keycap_Color = models.CharField(
        max_length= 20,
        choices = COLORS,
        default='BLA'
        )
    Keycap_Legend = models.CharField(
        max_length= 20,
        choices = TRUE_FALSE,
        default='TRUE'
        )
    Keycap_Shinethrough = models.CharField(
        max_length= 20,
        choices = TRUE_FALSE,
        default='TRUE'
        )

    
    def __str__(self):
        return self.name

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def get_absolute_url(self):
        return reverse('keyboards_index')

    
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        login(request,user)
        return redirect('index')
    else:
        error_message = "invalid sign-up, please try again."
    form = UserCreationForm()
    context = {"form": form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)




    

    




    # Create your models here.


#Keyboard model

#Case model with foreign key to keyboard
    # properties
        # name:
        # color:
        # material: 'plastic', 'polycarbonate', 'aluminum', 'acrylic', 'wood'
        # size : '100%/Full Sized', '80%/TKL', '75%', '65%', '60%', '40%'
        # layout: 'ANSI', 'ISO', 'Ortholinear'

# Plate model with foreign key to keyboard
    # properties
        # name
        # color
        # material: 'aluminium', 'brass', 'polycarbonate', 'steel', 'carbon fiber'

# switches model with foreign key to keyboard
    # properties
        # name
        # color:
        # switchstyle: 'clicky', 'silent', 'linear','tactile', 'optical'
        # RGB: (Y/N)


#keycaps model with foreign key to keyboard
    # Properties
        # name
        # color:
        # legend: (Y/N)
        # backlight_Shinethrough: (Y/N)

main_app/forms.py
from django.forms import ModelForm
from main_app.models import  Keyboard




class KeyboardForm(ModelForm):
    class Meta:
        model = Keyboard
        fields = ['name','description']

   

main_app/views.py
from multiprocessing import context
from .models import Keyboard
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

class KeyboardCreate(CreateView):
  model = Keyboard
  fields = '__all__'
  success_url = '/keyboards/'


def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def keyboards_index(request):


# Case Color Filter

  if request.GET.get('Case_Color'):
    featured_filter = request.GET.get('Case_Color')
    keyboards = Keyboard.objects.filter(Case_Color=featured_filter)
  else:
    keyboards = Keyboard.objects.all()
    
# Case Material Filter 
  if request.GET.get('Case_Material'):
    featured_filter2 = request.GET.get('Case_Material')
    keyboards = Keyboard.objects.filter(Case_Material=featured_filter2)
  elif request.GET.get('Case_Material') == '':
    keyboards = Keyboard.objects.all()

    # Case Size Filter 
  if request.GET.get('Case_Size'):
    featured_filter3 = request.GET.get('Case_Size')
    keyboards = Keyboard.objects.filter(Case_Size=featured_filter3)
  elif request.GET.get('Case_Size') == '':
    keyboards = Keyboard.objects.all()

    # Case Layout Filter 
  if request.GET.get('Case_Layout'):
    featured_filter4 = request.GET.get('Case_Layout')
    keyboards = Keyboard.objects.filter(Case_Layout=featured_filter4)
  elif request.GET.get('Case_Layout') == '':
    keyboards = Keyboard.objects.all()


# Plate Material Filter 
  if request.GET.get('Plate_Material'):
    featured_filter5 = request.GET.get('Plate_Material')
    keyboards = Keyboard.objects.filter(Plate_Material=featured_filter5)
  elif request.GET.get('Plate_Material') == '':
    keyboards = Keyboard.objects.all()

  if request.GET.get('Plate_Color'):
    featured_filter8 = request.GET.get('Plate_Color')
    keyboards = Keyboard.objects.filter(Plate_Color=featured_filter8)
  elif request.GET.get('Plate_Color') == '':
    keyboards = Keyboard.objects.all()

  # Switch Style Filter 
  if request.GET.get('Switch_Style'):
    featured_filter7 = request.GET.get('Switch_Style')
    keyboards = Keyboard.objects.filter(Switch_Style=featured_filter7)
  elif request.GET.get('Switch_Style') == '':
    keyboards = Keyboard.objects.all()

  # Switch Style Filter 
  if request.GET.get('Keycap_Color'):
    featured_filter9 = request.GET.get('Keycap_Color')
    keyboards = Keyboard.objects.filter(Keycap_Color=featured_filter9)
  elif request.GET.get('Keycap_Color') == '':
    keyboards = Keyboard.objects.all()

  return render(request, 'keyboards/index.html', {'keyboards': keyboards})
  

  

def keyboards_detail(request,keyboard_id):
  keyboard = Keyboard.objects.get(id = keyboard_id)
  return render(request,'keyboards/detail.html', {'keyboard': keyboard})

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request,user)
      return redirect('keyboards_index')
    else:
      error_message = "invalid sign-up, please try again."
  form = UserCreationForm()
  context = {"form": form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)





class KeyboardDelete(DeleteView):
  model = Keyboard
  success_url = '/keyboards/'

class KeyboardUpdate(UpdateView):
  model = Keyboard
  fields = '__all__'

main_app/templates/keyboards/detail.html
{% extends 'base.html' %}
{% block content %}


{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">



<h1>{{keyboard.name}}</h1>
<h1>{{keyboard.description}}</h1>
    <h2>Case</h2>
    <ul>
        <li>Case Color: {{keyboard.get_Case_Color_display}}</li>
        <li>Case Material: {{keyboard.get_Case_Material_display}}</li>
        <li>Plate Color: {{keyboard.get_Plate_Color_display}}</li>
        <li>Created by: {{keyboard.user}}</li>
        {% if user == keyboard.user %}
        <a href="{% url 'keyboards_delete' keyboard.id %}">Delete</a>
        <a href="{% url 'keyboards_update' keyboard.id %}">Edit</a>
        {% endif%}
    </ul>

    {% endblock %}

main_app/templates/keyboards/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<h1> List of Keyboards</h1>

<!-- form filter for Case Color -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Case Color</label>
    <select class = 'btn btn-secondary dropdown-toggle'name="Case_Color">
        <option value="" />Show All</option>
        <option value="BLA" />Black</option>
        <option value="RED" />Red</option>
        <option value="WHI" />White</option>
        <option value="BLU" />Blue</option>
        <option value="GRN" />Green</option>
        <option value="YLW" />Yellow</option>
        <option value="PRP" />Purple</option>
        <option value="ORG" />Orange</option>

    <input type="submit" class="btn btn-outline-dark btn-sm" name="Case_Color_Filtered" value="Filter" />
</form> 

<!-- form filter for Case Material -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Case Material</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Case_Material">
        <option value="" />Show All</option>
        <option value="PLA" />Plastic</option>
        <option value="POLY" />Polycarbonate</option>
        <option value="ALU" />Aluminum</option>
        <option value="ACR" />Acrylic</option>
        <option value="WOOD" />Wood</option>
        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Case_Material_Filtered" value="Filter" />
</form> 

<!-- form filter for Case Size -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Case Size</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Case_Size">
        <option value="" />Show All</option>
        <option value="100" />Full Size</option>
        <option value="80" />TKL</option>
        <option value="75" />75%</option>
        <option value="65" />65%</option>
        <option value="60" />60%</option>
        <option value="40" />40%</option>
        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Case_Size_Filtered" value="Filter" />
</form> 

<!-- form filter for Case Layout -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Case Layout</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Case_Layout">
        <option value="" />Show All</option>
        <option value="ANSI" />ANSI</option>
        <option value="ISO" />Isometric</option>
        <option value="ORTHO" />Ortholinear</option>
        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Case_Layout_Filtered" value="Filter" />
</form> 


<!-- form filter for Plate Material -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Plate Material</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Plate_Material">
        <option value="" />Show All</option>
        <option value="ALU" />Aluminum</option>
        <option value="BRS" />Brass</option>
        <option value="STL" />Steel</option>
        <option value="CBF" />Carbon Fiber</option>

        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Plate_Material_Filtered" value="Filter" />
</form> 

<!-- form filter for Plate Color -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Plate Color</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Plate_Color">
        <option value="" />Show All</option>
        <option value="BLA" />Black</option>
        <option value="RED" />Red</option>
        <option value="WHI" />White</option>
        <option value="BLU" />Blue</option>
        <option value="GRN" />Green</option>
        <option value="YLW" />Yellow</option>
        <option value="PRP" />Purple</option>
        <option value="ORG" />Orange</option>

        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Plate_Color_Filtered" value="Filter" />
</form> 


<!-- form filter for switches -->
<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Switch Style</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Switch_Style">
        <option value="" />Show All</option>
        <option value="CLI" />Clicky</option>
        <option value="SIL" />Silent</option>
        <option value="LIN" />Linear</option>
        <option value="TAC" />Tactile</option>
        <option value="OPT" />Optical</option>
        
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Switch_Style_Filtered" value="Filter" />
</form> 

<form action="{% url 'keyboards_index' %}" method="get">
    <label for="featured">Keycap Color</label>
    <select class = 'btn btn-secondary  btn-sm dropdown-toggle'name="Keycap_Color">
        <option value="" />Show All</option>
        <option value="BLA" />Black</option>
        <option value="RED" />Red</option>
        <option value="WHI" />White</option>
        <option value="BLU" />Blue</option>
        <option value="GRN" />Green</option>
        <option value="YLW" />Yellow</option>
        <option value="PRP" />Purple</option>
        <option value="ORG" />Orange</option>
    <input type="submit" class="btn btn-outline-dark btn-sm" name="Keycap_Color_Filtered" value="Filter" />
</form> 







<div class="row row-cols-6 row-cols-md-0 g-2">
{% for keyboard in keyboards %}

<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ keyboard.name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">By {{keyboard.user}}</h6>
      <p class="card-text">{{keyboard.description}}</p>
      <a href="{% url 'detail' keyboard.id %}" class="btn btn-outline-primary">Keyboard Details</a>
    </div>
  </div>

  {% endfor %}
</div>
  {% endblock %}